### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by MichalKononenko** [csferrie/python-qinfer#30]
I haven't gotten feedback on this project in 2 months. I can understand if this project is no longer in development, but I feel that qinfer does not yet have the web utilities needed in order to survive archiving.

It would be a good idea to ```pip freeze``` the project in a virtual environment, and use [requires.io](http://requires.io/) to track dependencies in the project. This would mean that even if one of our libraries were to be superceded by a major release, we wouldn't have any broken code. The repo would, however, get a notice and a happy little badge that would state that the code is out of date.

**Comment by cgranade** [comment]
No, it's not dead— far from it, in fact, as it is currently being used for quantum state and process tomography as well as for the original Hamiltonian learning and randomized benchmarking functionality. That said, I do apologize for the delay. As I said on #29, I was on extended travel when your PR was submitted. Since then, I have been fairly busy catching up, and unfortunately your PR slipped my mind.

In particular, #29 is a somewhat large PR and will take some time for me and the other collaborators on this project to sort through. I appreciate the submission, but I would ask for a bit more time to read through and provide the feedback that your contribution deserves. Thank you for reminding me to take a look, to be sure.

**Comment by MichalKononenko** [comment]
Thank you. Sorry if I came across as too rough. It's a great project and I'd love to help on it in any way I can.
